version: '3.6'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_NO_CACHE: "true"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/todos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: docker-todo-mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
      - MYSQL_DATABASE=todos
    ports:
      - "3310:3306"
    volumes:
      - ./mysql/sample_data/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 6s
      timeout: 3s
      retries: 5